# Generated by Django 6.0.2 on 2026-03-03 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=125, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('target_streak', models.PositiveSmallIntegerField(default=21, verbose_name='Цель(дней)')),
                ('current_streak', models.PositiveSmallIntegerField(default=0, verbose_name='Текущая серия')),
                ('best_streak', models.PositiveSmallIntegerField(default=0, verbose_name='Лучшая серия')),
                ('total_completions', models.PositiveSmallIntegerField(default=0, verbose_name='Всего выполнений')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(verbose_name='Отмечено в')),
                ('completed_date', models.DateField(db_index=True, verbose_name='Дата отметки')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('mood', models.CharField(blank=True, verbose_name='Самочувствие')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_logs', to='habit.habit', verbose_name='Привычка')),
            ],
            options={
                'verbose_name': 'Выполнение',
                'verbose_name_plural': 'Выполнения',
            },
        ),
    ]
